version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cardgame-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cardgame
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cardgame-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cardgame-pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cardgame.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - cardgame-network

volumes:
  postgres_data:

networks:
  cardgame-network:
    driver: bridge
